language: node_js
node_js:
  - "8"
addonsï¼š
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4775 /opt/google/chrome/chrome-sandbox"